#!/usr/bin/env node
// scripts/content/seed.mjs
//
// H1 content pipeline — seeder (docs/specs/H1-content-pipeline.md).
//
// Generates idempotent SQL (INSERT ... ON CONFLICT DO UPDATE) for the two
// tables A1's 0001_schema.sql creates EMPTY:
//   - topics_catalog(topic_id, position, level_count)  — one row per
//     src/data/registry.js TOPIC_UNLOCK_ORDER entry; position is the array
//     index; level_count is the number of `levelN` keys present in that
//     topic's `levels` object (3 for all five current topics).
//   - quiz_answer_keys(topic_id, level, answers int[]) — one row per quiz
//     level a topic actually has a `quiz` array for. In the current content,
//     that's level1 and level3 (level2 has no quiz) — 2 rows/topic x 5
//     topics = 10 rows total. answers[] is each quiz item's correctIndex,
//     in array order.
//
// By default this only GENERATES SQL (to stdout or --out <file>) — no DB
// connection is attempted. This environment has no local Docker/Supabase
// (see H1 handoff), so the SQL-generation path is what's actually exercised
// and tested here. --apply additionally shells out to `psql` against a
// caller-supplied connection string, for CI / anyone with a live DB.
//
// Usage:
//   node scripts/content/seed.mjs                      # print SQL to stdout
//   node scripts/content/seed.mjs --out seed.sql        # write SQL to a file
//   node scripts/content/seed.mjs --apply --db-url <url> [--out seed.sql]
//                                                       # also (or only,
//                                                       # if --out omitted)
//                                                       # apply the SQL via
//                                                       # `psql <url> -f -`
//
// `npm run content:seed` runs the default (stdout) form. See the H1 handoff
// note for the local `supabase start` + seed workflow B1 needs day 1.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { spawnSync } from 'node:child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..', '..')

// TOPIC_UNLOCK_ORDER is plain-ESM-exported from src/data/registry.js (H1,
// D-005 §3) — imported directly rather than re-parsed, so this seeder can
// never drift from the single source of truth.
const { TOPIC_UNLOCK_ORDER } = await import(join(REPO_ROOT, 'src', 'data', 'registry.js'))

function sqlQuote(str) {
  return `'${str.replace(/'/g, "''")}'`
}

function loadTopic(topicId) {
  const path = join(REPO_ROOT, 'src', 'data', `${topicId}.json`)
  return JSON.parse(readFileSync(path, 'utf8'))
}

export function buildSeedPlan() {
  const catalogRows = []
  const answerKeyRows = []

  TOPIC_UNLOCK_ORDER.forEach((topicId, position) => {
    const data = loadTopic(topicId)
    const levelKeys = Object.keys(data.levels ?? {})
    const levelCount = levelKeys.length

    catalogRows.push({ topicId, position, levelCount })

    for (const levelKey of levelKeys) {
      const levelNum = Number(levelKey.replace('level', ''))
      const quiz = data.levels[levelKey]?.quiz
      if (Array.isArray(quiz) && quiz.length > 0) {
        const answers = quiz.map((q) => q.correctIndex)
        answerKeyRows.push({ topicId, level: levelNum, answers })
      }
    }
  })

  return { catalogRows, answerKeyRows }
}

export function renderSql({ catalogRows, answerKeyRows }) {
  const lines = []
  lines.push('-- Generated by scripts/content/seed.mjs — DO NOT EDIT BY HAND.')
  lines.push('-- Idempotent: safe to run any number of times (ON CONFLICT DO UPDATE).')
  lines.push('begin;')
  lines.push('')

  lines.push('-- topics_catalog: one row per src/data/registry.js TOPIC_UNLOCK_ORDER entry.')
  for (const { topicId, position, levelCount } of catalogRows) {
    lines.push(
      `insert into public.topics_catalog (topic_id, position, level_count) values (${sqlQuote(topicId)}, ${position}, ${levelCount}) `
      + `on conflict (topic_id) do update set position = excluded.position, level_count = excluded.level_count;`,
    )
  }
  lines.push('')

  lines.push('-- quiz_answer_keys: one row per (topic, quiz-bearing level); answers[] = correctIndex in quiz order.')
  for (const { topicId, level, answers } of answerKeyRows) {
    const arrayLiteral = `ARRAY[${answers.join(', ')}]::int[]`
    lines.push(
      `insert into public.quiz_answer_keys (topic_id, level, answers) values (${sqlQuote(topicId)}, ${level}, ${arrayLiteral}) `
      + `on conflict (topic_id, level) do update set answers = excluded.answers;`,
    )
  }
  lines.push('')
  lines.push('commit;')
  lines.push('')
  return lines.join('\n')
}

function parseArgs(argv) {
  const opts = { out: null, apply: false, dbUrl: null }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--out') opts.out = argv[++i]
    else if (a === '--apply') opts.apply = true
    else if (a === '--db-url') opts.dbUrl = argv[++i]
    else {
      console.error(`unknown argument: ${a}`)
      process.exit(2)
    }
  }
  return opts
}

function main() {
  const opts = parseArgs(process.argv.slice(2))
  const plan = buildSeedPlan()
  const sql = renderSql(plan)

  if (opts.out) {
    writeFileSync(opts.out, sql, 'utf8')
    console.error(`content:seed: wrote ${plan.catalogRows.length} catalog row(s) + ${plan.answerKeyRows.length} answer-key row(s) to ${opts.out}`)
  } else if (!opts.apply) {
    process.stdout.write(sql)
  }

  if (opts.apply) {
    const dbUrl = opts.dbUrl ?? process.env.DATABASE_URL ?? process.env.SUPABASE_DB_URL
    if (!dbUrl) {
      console.error('SKIP content:seed --apply: no --db-url given and neither DATABASE_URL nor SUPABASE_DB_URL is set in the environment. Generated SQL was not applied to any database (this is expected in an environment with no local Supabase/Postgres — see H1 handoff).')
      process.exit(0)
    }
    const hasPsql = spawnSync('psql', ['--version'], { stdio: 'ignore' }).status === 0
    if (!hasPsql) {
      console.error('SKIP content:seed --apply: psql is not on PATH. Generated SQL was not applied.')
      process.exit(0)
    }
    const result = spawnSync('psql', [dbUrl, '-v', 'ON_ERROR_STOP=1', '-f', '-'], { input: sql, encoding: 'utf8' })
    if (result.status !== 0) {
      console.error(`FAIL content:seed --apply: psql exited ${result.status}`)
      console.error(result.stderr)
      process.exit(1)
    }
    console.error(`content:seed --apply: applied ${plan.catalogRows.length} catalog row(s) + ${plan.answerKeyRows.length} answer-key row(s) to ${dbUrl.replace(/:[^:@/]+@/, ':***@')}`)
  }

  process.exit(0)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main()
}
